### ISSUE TITLE
java.lang.NullPointerException en jetm.ReportGenerator

### ISSUE THREAD

**Issue by adrianudc** [adrianudc/vvs#8]
Stacktrace:

```
 java.lang.NullPointerException
        at jetm.contenido.EmisoraTest.testAgregarContenido(EmisoraTest.java:77)
        at jetm.ReportGenerator.executeEmisoraTests(ReportGenerator.java:72)
        at jetm.ReportGenerator.jetmReportGeneration(ReportGenerator.java:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
```

**Comment by adrianudc** [comment]
Fixed in commit e987b1b
